
package com.hubo.ws.spring.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.hubo.ws.spring.ObjectFactory;
import com.hubo.ws.spring.Order;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderWS", targetNamespace = "http://spring.ws.hubo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.hubo.ws.spring.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://spring.ws.hubo.com/", className = "com.hubo.ws.spring.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://spring.ws.hubo.com/", className = "com.hubo.ws.spring.GetByIdResponse")
    public Order getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
