
package com.hubo.ws.spring.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderWSImplService", targetNamespace = "http://impl.spring.ws.hubo.com/", wsdlLocation = "http://127.0.0.1:8080/spring_cxf_server/orderws?wsdl")
public class OrderWSImplService
    extends Service
{

    private final static URL ORDERWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.hubo.ws.spring.impl.OrderWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.hubo.ws.spring.impl.OrderWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/spring_cxf_server/orderws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/spring_cxf_server/orderws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public OrderWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWSImplService() {
        super(ORDERWSIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.spring.ws.hubo.com/", "OrderWSImplService"));
    }

    /**
     * 
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort() {
        return super.getPort(new QName("http://impl.spring.ws.hubo.com/", "OrderWSImplPort"), OrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.spring.ws.hubo.com/", "OrderWSImplPort"), OrderWS.class, features);
    }

}
