
package com.hubo.ws.student.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StudentWSImplService", targetNamespace = "http://impl.student.ws.hubo.com/", wsdlLocation = "http://127.0.0.1/service/studentWs?wsdl")
public class StudentWSImplService
    extends Service
{

    private final static URL STUDENTWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.hubo.ws.student.impl.StudentWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.hubo.ws.student.impl.StudentWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1/service/studentWs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1/service/studentWs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STUDENTWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public StudentWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWSImplService() {
        super(STUDENTWSIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.student.ws.hubo.com/", "StudentWSImplService"));
    }

    /**
     * 
     * @return
     *     returns StudentWS
     */
    @WebEndpoint(name = "StudentWSImplPort")
    public StudentWS getStudentWSImplPort() {
        return super.getPort(new QName("http://impl.student.ws.hubo.com/", "StudentWSImplPort"), StudentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentWS
     */
    @WebEndpoint(name = "StudentWSImplPort")
    public StudentWS getStudentWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.student.ws.hubo.com/", "StudentWSImplPort"), StudentWS.class, features);
    }

}
